services:
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static_volume:/data/static:ro
      - media_volume:/data/media:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: always
  web:
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py makemigrations --no-input && 
      python manage.py migrate --no-input && 
      python manage.py collectstatic --no-input && 
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --max-requests 500 --max-requests-jitter 50"
    restart: always
  db:
    image: postgres:14-alpine
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U formuser"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:
  media_volume:
  caddy_data:
  caddy_config:
